root: true
extends:
  - semistandard
  - plugin:prettier/recommended
rules:
  standard/computed-property-even-spacing: false
overrides:
  - files:
      - .mocharc.js
      - test
    parserOptions:
      sourceType: script
  - files:
      - test/**/*.spec.js
    env:
      mocha: true
    globals:
      expect: false
      sinon: false
      proxyquire: false
